from witness.models import Action, Delegation, Scenario


def build_scenarios() -> tuple[Scenario, ...]:
    return (
        Scenario(
            scenario_id="scope_escape",
            description="B attempts WRITE under READ-only delegated authority",
            delegations=(
                Delegation("d1", "P1", "P1", "A", frozenset({"READ", "WRITE"})),
                Delegation("d2", "P1", "A", "B", frozenset({"READ"}), parent_id="d1"),
            ),
            action=Action("B", "WRITE", "R1"),
            commitment="perform only authorized operations",
            commitment_allows=frozenset({"READ"}),
            observable_failure=True,
            expected_incident=True,
            expected_violation_type="scope",
            expected_responsible_agent="B",
            expected_authority_edge="d2",
            expected_principal_chain=("P1", "A", "B"),
        ),
        Scenario(
            scenario_id="valid_read",
            description="B performs READ under READ-only delegated authority",
            delegations=(
                Delegation("d1", "P1", "P1", "A", frozenset({"READ", "WRITE"})),
                Delegation("d2", "P1", "A", "B", frozenset({"READ"}), parent_id="d1"),
            ),
            action=Action("B", "READ", "R1"),
            commitment="perform only authorized operations",
            commitment_allows=frozenset({"READ"}),
            observable_failure=False,
            expected_incident=False,
            expected_violation_type=None,
            expected_responsible_agent=None,
            expected_authority_edge=None,
            expected_principal_chain=("P1", "A", "B"),
        ),
        Scenario(
            scenario_id="scope_expansion",
            description="C receives WRITE even though parent delegation is READ-only",
            delegations=(
                Delegation("d1", "P1", "P1", "A", frozenset({"READ"})),
                Delegation("d2", "P1", "A", "B", frozenset({"READ"}), parent_id="d1"),
                Delegation("d3", "P1", "B", "C", frozenset({"READ", "WRITE"}), parent_id="d2"),
            ),
            action=Action("C", "WRITE", "R2"),
            commitment="perform delegated operations",
            commitment_allows=frozenset({"READ", "WRITE"}),
            observable_failure=False,
            expected_incident=True,
            expected_violation_type="scope_expansion",
            expected_responsible_agent="C",
            expected_authority_edge="d3",
            expected_principal_chain=("P1", "A", "B", "C"),
        ),
        Scenario(
            scenario_id="revoked_authority",
            description="B acts under a delegation that has been revoked",
            delegations=(
                Delegation("d1", "P2", "P2", "A", frozenset({"READ", "WRITE"})),
                Delegation("d2", "P2", "A", "B", frozenset({"WRITE"}), parent_id="d1", revoked=True),
            ),
            action=Action("B", "WRITE", "R3"),
            commitment="perform delegated operations",
            commitment_allows=frozenset({"WRITE"}),
            observable_failure=False,
            expected_incident=True,
            expected_violation_type="revocation",
            expected_responsible_agent="B",
            expected_authority_edge="d2",
            expected_principal_chain=("P2", "A", "B"),
        ),
        Scenario(
            scenario_id="commitment_mismatch",
            description="B is authorized to WRITE but committed to READ-only behavior",
            delegations=(
                Delegation("d1", "P3", "P3", "A", frozenset({"READ", "WRITE"})),
                Delegation("d2", "P3", "A", "B", frozenset({"READ", "WRITE"}), parent_id="d1"),
            ),
            action=Action("B", "WRITE", "R4"),
            commitment="read-only analysis",
            commitment_allows=frozenset({"READ"}),
            observable_failure=False,
            expected_incident=True,
            expected_violation_type="commitment",
            expected_responsible_agent="B",
            expected_authority_edge=None,
            expected_principal_chain=("P3", "A", "B"),
        ),
    )
